---

toolshedservers_group_packages:
  - htop
  - strace
  - dstat
  - tmux
  - vim
  - tmpwatch

toolshedservers_group_authorized_key_users: "{{ vault_toolshedservers_group_authorized_key_users }}"

toolshedservers_group_groups:
  - name: shed
    gid: 899
    system: yes
  - name: gxsrc
    gid: 898
    system: yes

toolshedservers_group_users:
  - name: shed
    comment: "Galaxy Tool Shed"
    uid: 899
    group: shed
    home: /home/shed
    shell: /bin/bash
    system: yes
  - name: gxsrc
    comment: "Galaxy Source Code"
    uid: 898
    group: gxsrc
    home: /home/gxsrc
    shell: /bin/bash
    system: yes
