---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_users:
  - name: launch
    comment: 'Galaxy Cloud Launch'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'
  - name: sites
    comment: 'Web sites'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'
  - name: gxsite
    comment: 'Galaxy site'
    system: 'yes'
    shell: '/bin/bash'

host_directories:
  - path: /srv/cloudlaunch
    owner: launch
    group: launch
  - path: /srv/nginx
    owner: sites
    group: sites
  - path: /srv/nginx/new.galaxyproject.org/root
    owner: gxsite
    group: gxsite
  - path: /srv/nginx/biostar.usegalaxy.org/root
    owner: gxsite
    group: gxsite

nginx_flavor: full

# TODO: disable 1.0, 1.1
nginx_conf_ssl_protocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 1g
  proxy_read_timeout: 3600

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - galaxyproject
  - cloudlaunch
  - gxy.io
  - biostar
