---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_users:
  - name: gxsite
    comment: 'Galaxy site'
    system: 'yes'
    shell: '/bin/bash'

host_directories:
  - path: /srv/nginx
    owner: sites
    group: sites

nginx_flavor: full

# TODO: disable 1.0, 1.1
nginx_conf_ssl_protocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 1g
  proxy_read_timeout: 3600

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - galaxyproject

certbot_domains:
  - galaxyproject.org

# athena is old
certbot_post_renewal: |
    service nginx restart || true
