---

- name: Tasks for web servers
  hosts: webservers
  pre_tasks:
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    # galaxyproject.nginx will run usegalaxy_eu.certbot
    - role: galaxyproject.nginx
  tags: 
    - nginx
