---

- name: Install packages
  package:
    name: "{{ ldap_server_packages }}"

- name: Include LDAP implementation tasks
  include_tasks: "{{ ldap_server_implementation | lower }}.yml"

- name: Ensure LDAP server is enabled and running
  service:
    name: "{{ ldap_server_service_name }}"
    state: started
    enabled: yes
