---
- name: galaxyproject.nginx
- name: galaxyproject.mailman3
  src: https://github.com/galaxyproject/ansible-mailman3
- name: galaxyproject.postfix
  src: https://github.com/galaxyproject/ansible-postfix
- name: galaxyproject.postgresql
- name: usegalaxy-eu.certbot
  src: https://github.com/usegalaxy-eu/ansible-certbot
- name: galaxyproject.slurm
  version: 0.1.1
- name: galaxyproject.cvmfs
  version: 0.2.2
- name: geerlingguy.repo-epel
  version: 1.2.3
- name: dj-wasabi.telegraf
  version: 0.12.0
