---

- name: Install packages for LDAP client
  package:
    name: "{{ __ldap_packages }}"

- name: Install OpenLDAP ldap.conf
  template:
    src: ldap.conf.j2
    dest: "{{ ldap_ldap_conf_path }}"
    mode: 0444
    backup: yes

- include_tasks: nss.yml
  when: inventory_hostname in groups['ldapnssclients']
