---

smartos_root_authorized_keys: "{{ vault_smartos_root_authorized_keys }}"

smartos_resolvers:
  - 128.118.250.8
  - 3.14.178.173
  - 3.136.94.7

smartosglobalzones_group_directories:
  - path: /usbkey/config.inc

smartosglobalzones_group_files:
  - dest: /usbkey/config.inc/root_authorized_keys
    content: |
      ### This file is managed by Ansible.  ALL CHANGES WILL BE OVERWRITTEN.
      {% for user in smartos_root_authorized_keys %}
      {{ sshkeys[user] }}
      {% endfor %}
