---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_users:
  - name: sites
    comment: 'Web sites'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'

host_directories:
  - path: /srv/nginx
    owner: sites
    group: sites

#mounts:
#  - name: /var/mail
#    src: /dev/xvdn
#    fstype: xfs
#    mode: 2775
#    owner: root
#    group: mail

ldap_server_uris:
  - ldap://localhost/ # prefer self
  - ldap://ldap1.galaxyproject.org/
  - ldap://ldap3.galaxyproject.org/

nginx_servers:
  - certbot_redirects_infra

nginx_ssl_servers:
  - wiki
#  - moin
  - galaxydomains
  - new
  - training

certbot_domains:
  - wiki.g2.bx.psu.edu
  - wiki.galaxyproject.org
  #- moin.galaxyproject.org
  - galaxy2.org
  - galaxyworkbench.org
  - repeatme.org
  - galaxy.psu.edu
  - galaxycast.org
  - getgalaxy.org
  - new.galaxyproject.org
  - training.galaxyproject.org

nginx_extra_configs:
  - wiki_hub_rewrites.conf

nginx_default_redirect_uri: https://galaxyproject.org/
