---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_users:
  - name: sites
    comment: 'Web sites'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'
  - name: gxsite
    comment: 'Galaxy site'
    system: 'yes'
    shell: '/bin/bash'

host_directories:
  - path: /srv/nginx
    owner: sites
    group: sites
  - path: /srv/nginx/new.galaxyproject.org/root
    owner: gxsite
    group: gxsite

mounts:
  - name: /var/mail
    src: /dev/xvdn
    fstype: xfs
    mode: 2775
    owner: root
    group: mail

ldap_server_uris:
  - ldap://localhost/ # prefer self
  - ldap://ldap1.galaxyproject.org/
  - ldap://ldap3.galaxyproject.org/

nginx_servers:
  - certbot_redirects_infra

nginx_ssl_servers:
  - wiki
  - moin
  - intron
  - galaxydomains
  - new
  - training

certbot_domains:
  - "{{ inventory_hostname }}"
  - wiki.g2.bx.psu.edu
  - wiki.galaxyproject.org
  - moin.galaxyproject.org
  - intron.galaxyproject.org
  - galaxy2.org
  - galaxyworkbench.org
  - repeatme.org
  - galaxy.psu.edu
  - galaxycast.org
  - getgalaxy.org
  - new.galaxyproject.org
  - training.galaxyproject.org

nginx_extra_configs:
  - wiki_hub_rewrites.conf

# not implemented
#nginx_pam_config_src: pam_galaxy
#nginx_pam_config_dest: /etc/pam.d/nginx

nginx_default_redirect_uri: https://galaxyproject.org/
