---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"
cvmfs_private_keys: "{{ vault_cvmfs_private_keys }}"

galaxy_cvmfs_repos_enabled: false
cvmfs_repositories:
  - repository: data.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
      - CVMFS_IGNORE_XDIR_HARDLINKS=false
    client_options: []
  - repository: sandbox.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: sandbox
    server_options:
      - CVMFS_GARBAGE_COLLECTION=true
    client_options: []
  - repository: singularity.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: singularity
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: usegalaxy.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: usegalaxy
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: cvmfs-config.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: root
    server_options:
      - CVMFS_GARBAGE_COLLECTION=true
    client_options: []

host_users:
  - name: g2test
    uid: 819456
    group: G-803372
    comment: "Galaxy Test"
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    uid: 819800
    group: G-803372
    comment: "Galaxy Main"
    home: /home/g2main
    shell: /bin/bash
  - name: sandbox
    comment: "CVMFS Sandbox"
    home: /home/sandbox
    shell: /bin/bash
    system: true
    groups: docker
  - name: singularity
    comment: "Singularity Images"
    home: /home/singularity
    shell: /bin/bash
    system: yes
  - name: usegalaxy
    comment: "UseGalaxy Common Data"
    home: /home/usegalaxy
    shell: /bin/bash
    system: yes

host_groups:
  - name: G-803372
    gid: 803372
