---

default_locale: en_US.UTF-8

zfs_filesystems:
  - name: zones/bf060497-c4e2-4431-a60d-b879dfd02620/data/srv
    mountpoint: /srv
    setuid: "off"
  - name: zones/bf060497-c4e2-4431-a60d-b879dfd02620/data/srv/toolshed-repos
    mountpoint: /srv/toolshed-repos
    exec: "off"
    setuid: "off"
    compression: "lz4"
  - name: zones/bf060497-c4e2-4431-a60d-b879dfd02620/data/postgres
    mountpoint: /var/lib/postgresql
    exec: "off"
    setuid: "off"

host_directories:
  - path: /srv/toolshed-repos/test
    owner: shed
    group: shed
    mode: "0750"
