---

host_directories:
  - path: /srv/nginx/datacache.galaxyproject.org/root

host_files:
  - src: files/sites/datacache/index.html
    dest: /srv/nginx/datacache.galaxyproject.org/root/index.html

host_packages:
  - rsync

host_services:
  - name: rsyncd
    state: started
    enabled: 'yes'

host_templates:
  - dest: /etc/rsyncd.conf
    src: ini.j2
    contents:
      indexes:
        path: /cvmfs/data.galaxyproject.org/byhand
        comment: Galaxy Genome Indexes
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'
        exclude: '*/tmp/* */work/* bin/*'
      location:
        path: /cvmfs/data.galaxyproject.org/byhand/location
        comment: Galaxy Data Location Files
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'
      managed:
        path: /cvmfs/data.galaxyproject.org/managed
        comment: Managed Galaxy Data
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'
      byhand:
        path: /cvmfs/data.galaxyproject.org/byhand
        comment: Alternate mount point for /indexes/ for rsync data manager
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'
        exclude: '*/tmp/* */work/* bin/*'

host_firewall_rules:
  - service: http
    state: enabled
    permanent: yes
    immediate: yes
  - service: rsyncd
    state: enabled
    permanent: yes
    immediate: yes
  - port: 2377/tcp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 2377/tcp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/tcp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/tcp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/udp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/udp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 4789/udp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 4789/udp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes

# datacache.galaxyproject.org
nginx_enable_default_server: false
nginx_configs:
  - datacache
