---

host_directories:
  - path: /srv/nginx

ldap_server_uris:
  - ldap://localhost/ # prefer self
  - ldap://ldap2.galaxyproject.org/
  - ldap://ldap3.galaxyproject.org/

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - wiki
  - galaxydomains
  - gxy.io

certbot_domains:
  - newtrail.galaxyproject.org
  - wiki.g2.bx.psu.edu
  - wiki.galaxyproject.org
  - galaxy2.org
  - galaxyworkbench.org
  - repeatme.org
  - g2.bx.psu.edu
  - galaxy.psu.edu
  - galaxycast.org
  - getgalaxy.org
  - galaxy.training
  - new.galaxyproject.org
  - gxy.io

nginx_extra_configs:
  - wiki_hub_rewrites.conf

nginx_default_redirect_uri: https://galaxyproject.org/
