
---

smartos_images:
  # base-64 19.2.0 smartos  zone-dataset
  - uuid: f3a6e1a2-9d71-11e9-9bd2-e7e5b4a5c141
    state: present

smartos_vms:
  - name: orval
    brand: joyent
    image_uuid: f3a6e1a2-9d71-11e9-9bd2-e7e5b4a5c141
    hostname: orval
    max_physical_memory: 8192
    quota: 32
    resolvers: "{{ smartos_resolvers }}"
    nics:
      - nic_tag: external
        ip: "{{ lookup('dig', 'orval.galaxyproject.org') }}"
        netmask: 255.255.255.224
        gateway: 128.118.250.1
        vlan_id: 306
    delegate_dataset: true
    customer_metadata:
      root_authorized_keys: "{{ sshkeys.nate_coraor }}"
      user-script: "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys ; /usr/sbin/mdata-get root_authorized_keys > ~admin/.ssh/authorized_keys"
