---

smartos_images:
  # centos-7 20180323 linux lx-dataset
  - uuid: 3dbbdcca-2eab-11e8-b925-23bf77789921
    state: present

smartos_vms:
  - name: cvmfs1-psu0
    brand: lx
    kernel_version: 3.10.0-1062.1.2.el7.x86_64
    image_uuid: 3dbbdcca-2eab-11e8-b925-23bf77789921
    hostname: cvmfs1-psu0
    max_physical_memory: 8192
    quota: 32768
    resolvers: "{{ smartos_resolvers }}"
    nics:
      - nic_tag: admin
        ip: 128.118.250.10
        netmask: 255.255.255.224
        gateway: 128.118.250.1
        vlan_id: 306
    delegate_dataset: true
    customer_metadata:
      root_authorized_keys: "{{ sshkeys.nate_coraor }}"
