---

smartos_images:
  # centos-7 20190122 linux zvol
  - uuid: d6e56c0e-1e51-11e9-8ff1-2fecf38a5566
    state: present

smartos_vms:
  - name: cvmfs0-psu0
    brand: bhyve
    ram: 16384
    vcpus: 4
    resolvers: "{{ smartos_resolvers }}"
    nics:
      - nic_tag: external
        ip: "{{ lookup('dig', 'cvmfs0-psu0.galaxyproject.org') }}"
        netmask: 255.255.255.224
        gateway: 128.118.250.1
        vlan_id: 306
        model: virtio
    disks:
      - image_uuid: d6e56c0e-1e51-11e9-8ff1-2fecf38a5566
        boot: true
        model: virtio
      # /var/spool/cvmfs
      - boot: false
        model: virtio
        size: 4194304
      # /srv
      - boot: false
        model: virtio
        size: 25165824
    customer_metadata:
      root_authorized_keys: "{{ sshkeys.nate_coraor }}"
