---

slurm_dbd_mysql_pass: "{{ vault_slurm_dbd_mysql_pass }}"

mariadb_root_pass: "{{ vault_mariadb_root_pass }}"
mariadb_options:
  innodb_buffer_pool_size: 1024M
  innodb_log_file_size: 64M
  innodb_lock_wait_timeout: 900
mariadb_users: "{{ vault_mariadb_users }}"
mariadb_databases:
  - name: slurm_acct_db
