---

- name: Tasks for "galaxyproject.org environment" hosts
  hosts: galaxyenv
  remote_user: root
  roles: []
    # TODO: this should probably not run on guest instances, but also, when is this still needed?
    #- role: resolv         # Set resolv.conf for static hosts
    #  tags: initial,resolv
    # TODO: switch to galaxyproject.postfix
    #- role: postfix         # MX and null client configuration
    #  tags: mail,postfix
  tags: initial,galaxyenv
