---

- name: Tasks for "base environment" hosts
  hosts: baseenv
  remote_user: root
  roles:
    - role: requiretty        # Disable requiretty for Ansible ssh pipelining
      tags: initial,requiretty
    - role: remote_management # Set up IPMI/serial stuff
      tags: initial,remote_management
    - role: ssh               # Enable password auth and root logins
      tags: initial,ssh
    - role: timezone          # Configure system timezone
      tags: initial,timezone
    - role: packages          # Install packages
      tags: system,packages
    - role: users             # Create users and set up authentication keys
      tags: system,users
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: copy              # Copy arbitrary files/templates
      tags: system,copy
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: firewall          # Configure host firewall
      tags: system,firewall
    - role: services          # Manage services
      tags: system,services
  tags: initial,baseenv
  handlers:
    - include: _inc_handlers.yml
