---

- name: Get EC2 Facts
  hosts: ec2hosts
  remote_user: root
  tasks:
    - name: Get EC2 Facts
      action: ec2_metadata_facts
  tags: always

- name: Tasks for virtualized hosts
  hosts: virtual
  remote_user: root
  roles:
    - virtual
  tags: initial,system

- name: Include baseenv plays
  import_playbook: _inc_baseenv.yml

- name: Set up authentication keys for non-baseenv hosts
  hosts: authkeyhosts
  remote_user: root
  roles:
    - users
  tags: users

- name: Tasks for infrastructure servers
  hosts: infrastructure
  remote_user: root
  gather_facts: false
  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags: always
  roles:
    - name: required_vars
      required_vars_roles:
        - kerberos_kdc
        - ldap_server
      tags: always
    - name: kerberos_kdc
      tags: kerberos_kdc,kerberos
    - name: dns
      tags: dns
    - name: ldap_server
      tags: ldap
    - name: ldap
      tags: ldap
  tags: infrastructure

- name: Tasks for webservers
  hosts: webservers
  remote_user: root
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - role: galaxyproject.nginx
  tags: nginx
