---

- name: Check for iprop keytab
  stat:
    path: "{{ kerberos_kdc_iprop_keytab }}"
  register: _ret_iprop_keytab_stat

- name: Include heimdal keytab tasks
  include: heimdal_keytab.yml
  when: not _ret_iprop_keytab_stat.stat.exists

- name: Install iprop replicas file
  template:
    src: replicas.j2
    dest: "{{ kerberos_kdc_replicas_file }}"
    mode: "0444"
    backup: yes
  when: "'kerberosprimaryservers' in group_names"

- name: Ensure inetd is running (for kadmind)
  service:
    name: "{{ kerberos_kdc_inetd_service_name }}"
    state: "started"
    enabled: yes
  when: "'kerberosprimaryservers' in group_names"
