---

cvmfs_role: client
slurm_roles:
  - exec

slurm_munge_key: files/slurm/munge.key

galaxy_cvmfs_repos_enabled: true

galaxy_cvmfs_server_urls:
  - domain: galaxyproject.org
    use_geoapi: true
    urls:
      - "http://cvmfs1-{{ cloud_id[10:] }}0.jetstreamlocal/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"

cvmfs_http_proxies:
  - "http://jetstream-{{ cloud_id[10:] }}0.jetstreamlocal:3128"
  - "DIRECT"

slurm_user:
  uid: 40302
  gid: 40302
  comment: 'Slurm Workload Manager'
  home: /var/lib/slurm
  shell: /bin/bash

jetstream_nfs_filesystems:
  - device: "{{ controller_name }}.jetstreamlocal:/jetstream/scratch0"
    dir: scratch0

directories:
  - path: /galaxy-repl/test
    mode: "0755"
  - path: /galaxy-repl/main
    mode: "0755"
  - path: /var/lib/slurm
    mode: "0755"

# symlinks for deps must exist due to path issues
links:
  - dest: /galaxy
    src: /galaxy-repl
  - dest: /galaxy-repl/test/deps
    src: /cvmfs/test.galaxyproject.org/deps
  - dest: /galaxy-repl/test/tool_data
    src: /cvmfs/data.galaxyproject.org/byhand/location
  - dest: /galaxy-repl/main/deps
    src: /cvmfs/main.galaxyproject.org/deps
  - dest: /galaxy-repl/main/tool_data
    src: /cvmfs/data.galaxyproject.org/byhand/location
