---

cvmfs_private_keys: "{{ vault_cvmfs_private_keys }}"

cvmfs_repositories:
  - repository: test.galaxyproject.org
    stratum0: cvmfs0-tacc0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
      - CVMFS_IGNORE_XDIR_HARDLINKS=true
      - CVMFS_GENERATE_LEGACY_BULK_CHUNKS=false
      - CVMFS_VIRTUAL_DIR=true
    client_options:
      - CVMFS_NFILES=4096
  - repository: main.galaxyproject.org
    stratum0: cvmfs0-tacc0.galaxyproject.org
    owner: g2main
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
      - CVMFS_IGNORE_XDIR_HARDLINKS=true
      - CVMFS_GENERATE_LEGACY_BULK_CHUNKS=false
      - CVMFS_VIRTUAL_DIR=true
    client_options:
      - CVMFS_NFILES=4096


# old docker repo, docker now installed by the `docker` role
host_yum_repositories:
  - name: dockerrepo
    state: absent
    #contents:
    #  name: Docker Repository
    #  state: absent
