---

- name: Create zones directory
  file:
    state: directory
    path: "{{ dns_bind_zones_dir }}"
    group: "{{ dns_group }}"
    mode: "0775"
  when: "'dnsmasterservers' in group_names"

- name: Create slave/journal directory
  file:
    state: directory
    path: "{{ dns_bind_slave_zones_dir }}"
    group: "{{ dns_group }}"
    mode: "0770"

- name: Disable inclusion of named.conf.default-zones
  replace:
    dest: "{{ dns_config_dir }}/named.conf"
    regexp: '^(include "/etc/bind/named.conf.default-zones";)'
    replace: '#\1'
    backup: yes
  notify:
    - restart dns
