---

- name: Install packages
  package:
    name: "{{ dns_packages }}"

- name: Include DNS implementation tasks
  include_tasks: "{{ dns_implementation | lower }}.yml"

- name: Create DNS log directory
  file:
    state: directory
    dest: "{{ dns_log_dir }}"
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0755"
  when: dns_log_dir is not none and dns_log_dir != ""

- name: Install config files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ dns_config_dir }}/{{ item.dest }}"
    # this owner/mode scheme matches what debian does, even though it doesn't really make sense
    group: "{{ dns_group }}"
    mode: "0440"
    backup: yes
  with_items: "{{ dns_config_templates }}"
  notify:
    - restart dns

- name: Ensure DNS server is enabled and running
  service:
    name: "{{ dns_service_name }}"
    state: started
    enabled: yes
