---

dns_bind_views:
  - name: 'galaxy'
    match_clients:
      - '!key certbot.'
      - '!key axfr-global.'
      - 'key axfr-galaxy.'
      - 'galaxy'
      - 'bx'
    recursion: yes
    includes:
      - '{{ dns_config_dir }}/named.conf.default-zones'
    also_notify:
      - '3.136.94.7 key axfr-galaxy.'       # artifact
      - '54.172.173.123 key axfr-galaxy.'   # chouffe
      - '128.118.250.8 key axfr-galaxy.'    # duvel
    zones:
      - name: 'galaxyproject.org'
        file: 'galaxyproject.org.private.zone'
      - file: 'usegalaxy.org.zone'
      - file: 'getgalaxy.org.zone'
      - file: 'galaxycast.org.zone'
      - file: 'repeatme.org.zone'
      - file: 'galaxy2.org.zone'
      - file: 'galaxyworkbench.org.zone'
      - file: 'galaxy.tools.zone'
      - file: 'toolshed.tools.zone'
      - file: 'gxy.io.zone'
      - file: 'galaxy.training.zone'
      #- file: '0-27.250.118.128.in-addr.arpa.zone'
      - file: '0.18.172.in-addr.arpa.zone'
      - file: '2.18.172.in-addr.arpa.zone'
      - file: '3.18.172.in-addr.arpa.zone'
      - file: '68.28.172.in-addr.arpa.zone'
      - file: '255.128.10.in-addr.arpa.zone'
  - name: 'global'
    match_clients:
      - 'key certbot.'
      - '!key axfr-galaxy.'
      - 'key axfr-global.'
      - '!galaxy'
      - '!bx'
      - 'any'
    also_notify:
      - '3.136.94.7 key axfr-global.'       # artifact
      - '54.172.173.123 key axfr-global.'   # chouffe
      - '128.118.250.8 key axfr-global.'    # duvel
    zones:
      - file: 'galaxyproject.org.zone'
        update_policy:
          - 'grant certbot. zonesub TXT'
      - file: 'usegalaxy.org.zone'
      - file: 'getgalaxy.org.zone'
      - file: 'galaxycast.org.zone'
      - file: 'repeatme.org.zone'
      - file: 'galaxy2.org.zone'
      - file: 'galaxyworkbench.org.zone'
      - file: 'galaxy.tools.zone'
      - file: 'toolshed.tools.zone'
      - file: 'gxy.io.zone'
      - file: 'galaxy.training.zone'
      #- file: '0-27.250.118.128.in-addr.arpa.zone'
