---

- name: Create Grafana systemd config
  copy:
    src: "{{ ansible_os_family | lower }}/{{ grafana_service_name }}.service"
    dest: "/etc/systemd/system/{{ grafana_service_name }}.service"
  register: stats_grafana_service_unit_file

- name: Ensure InfluxDB is started and running
  service:
    name: "{{ influxdb_service_name }}"
    state: started
    enabled: yes

- name: Ensure Grafana is started and running
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: yes
    daemon_reload: "{{ 'yes' if stats_grafana_service_unit_file is changed else 'no' }}"
