---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_users:
  - name: docs
    comment: 'Galaxy Docs'

mounts:
  - name: /srv/nginx/wheels_eggs
    src: /dev/xvdl
    fstype: xfs

ldap_server_uris:
  - ldap://ldap1.galaxyproject.org/
  - ldap://ldap2.galaxyproject.org/
  - ldap://ldap3.galaxyproject.org/

nginx_conf_ssl_protocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2

nginx_servers:
  - certbot_redirects_infra
  - eggs

nginx_ssl_servers:
  - eggs-ssl
  - galaxydomains
  - toolshed.tools
  - galaxy.tools
  - docs

certbot_redirect_domains:
  - "{{ inventory_hostname }}"
  - toolshed.tools
  - galaxy.tools
  - docs.galaxyproject.org

certbot_domains:
  - "{{ inventory_hostname }}"
  - eggs.galaxyproject.org
  - eggs.g2.bx.psu.edu
  - toolshed.tools
  - galaxy.tools
  - docs.galaxyproject.org

nginx_default_redirect_uri: https://galaxyproject.org/
