---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

mounts:
  - name: /srv/nginx/wheels_eggs
    src: /dev/xvdl
    fstype: xfs

ldap_server_uris:
  - ldap://ldap1.galaxyproject.org/
  - ldap://ldap2.galaxyproject.org/
  - ldap://ldap3.galaxyproject.org/

nginx_conf_ssl_protocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2

nginx_default_redirect_uri: https://galaxyproject.org/
