---

- name: Stop instance(s)
  hosts: galaxynodes
  connection: local
  environment:
     OS_CLOUD: "{{ cloud_id }}"
     OS_IDENTITY_API_VERSION: '3'
  tasks:
    - name: Destroy instance
      os_server:
        cloud: "{{ cloud_id }}"
        name: "{{ inventory_hostname }}"
        state: absent
      delegate_to: localhost
      become: false
