---

ldap_server_base_dn: dc=galaxyproject,dc=org

# this order is significant, it controls the order of schema loading
ldap_server_openldap_schemas:
  - core
  - cosine
  - rfc2307bis
  - inetorgperson
  - sudo
  - galaxy
  - postfix
  - dhcp
  - autofs

ldap_server_openldap_config:
  modules:
    - back_mdb
    - syncprov
    - refint
    - unique
    - valsort
  databases:
    - module: mdb
      indexes:
        - entryUUID
        - cn
        - dhcpHWAddress
        - mail
        - surname
        - givenName
        - memberUid
        - objectClass
        - attrib: mailRoutingAddress
          type: sub
        - uid
        - uidNumber
        - uniqueMember
      overlays:
        - module: refint
          options:
            - refint_attributes: member
        - module: unique
          options:
            - unique_uri: ldap:///ou=group,dc=galaxyproject,dc=org?gidNumber?sub?
            - unique_uri: ldap:///ou=people,dc=galaxyproject,dc=org?uidNumber?sub?
            - unique_uri: ldap:///ou=hosts,cn=config,ou=dhcp,dc=galaxyproject,dc=org?dhcpHWAddress?sub?
        - module: valsort
          options:
            - valsort-attr: memberUid ou=group,dc=galaxyproject,dc=org alpha-ascend
            - valsort-attr: member ou=group,dc=galaxyproject,dc=org alpha-ascend
      syncrepl:
        provider: newtrail.galaxyproject.org


ldap_server_openldap_access: "{{ vault_ldap_server_openldap_access }}"

# only used by OLC tasks
#ldap_server_openldap_syncrepl_config:
#  provider: delirium.galaxyproject.org
