---
# TS in JS

os_name: "{{ inventory_hostname_short }}"
os_flavor: m1.medium
os_auto_ip: true
os_cloud_id: "jetstream_tacc"
os_key_name: "nate_jetstream"
os_nics: "net-name={{ os_network.name }}"
os_security_groups: "default,infrastructure-sg"

# fstype isn't used by any of the openstack modules, but both mounts and filesystems need it, and putting it in
# os_volumes avoids circular references. See the "Write volume device(s) to host_vars" task in the Jetstream playbook.
os_volumes:
  - name: "{{ inventory_hostname_short }}-pgsql"
    size: 64
    fstype: xfs
  - name: "{{ inventory_hostname_short }}-srv"
    size: 128
    fstype: xfs

#filesystems: is set automatically by the playbook in os_volume_devices.yml

# this is parallel with os_volumes and filesystems
mounts:
  - path: /var/lib/pgsql
    # user does not exist yet
    #owner: postgres
    #group: postgres
    src: "{{ filesystems[0].dev }}"
    fstype: "{{ os_volumes[0].fstype }}"
  - path: /srv
    src: "{{ filesystems[1].dev }}"
    fstype: "{{ os_volumes[1].fstype }}"
