---

jenkinsslaves_group_authorized_key_users: "{{ vault_jenkinsslaves_group_authorized_key_users }}"
jenkinsslaves_group_private_key_users: "{{ vault_jenkinsslaves_group_private_key_users }}"

# hopefully overrides config-repo in cvmfsclients.yml
galaxy_cvmfs_repos_enabled: true

_jenkinsslaves_openjdk_version: "{{ '11' if ansible_distribution == 'Debian' and ansible_distribution_major_version == '10' else '8' }}"
jenkinsslaves_group_packages:
  - git
  - openjdk-{{ _jenkinsslaves_openjdk_version }}-jre-headless
  - ntp
  - ntpdate
  - build-essential
  - curl
  - pandoc
  - python3-venv
  # for usegalaxy-tools
  #- fuse-overlayfs
  - tree
  - rsync

# Moved to a post-task
#jenkinsslaves_group_users:
#  - name: jenkins
#    groups: docker
#    system: true

jenkinsslaves_group_directories:
  - path: ~jenkins/bin
    owner: jenkins
    group: jenkins

jenkinsslaves_group_files:
  - src: files/jenkins/jenkins_slave_user_ssh_config
    dest: ~jenkins/.ssh/config
    owner: jenkins
    group: jenkins
  - src: files/jenkins/tmpfiles.d-clean-tmp.conf
    dest: /etc/tmpfiles.d/clean-tmp.conf

jenkinsslaves_group_kernel_params:
  - name: net.ipv4.tcp_keepalive_time
    value: 300
  - name: net.ipv4.tcp_keepalive_intvl
    value: 30
  - name: net.ipv4.tcp_keepalive_probes
    value: 40
