---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

cvmfs_stratum1_squid_conf_src: templates/squid/cvmfs1-psu0_squid.conf.j2
cvmfs_stratum1_cache_mem: 1024

cvmfs_srv_device: /dev/vdb

cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://localhost/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"

host_directories:
  - path: /srv/nginx/datacache.galaxyproject.org/root

host_files:
  - src: files/sites/datacache/index.html
    dest: /srv/nginx/datacache.galaxyproject.org/root/index.html

host_packages:
  - rsync

host_services:
  - name: rsyncd
    state: started
    enabled: 'yes'

host_templates:
  - dest: /etc/rsyncd.conf
    src: ini.j2
    contents:
      indexes:
        path: /cvmfs/data.galaxyproject.org/byhand
        comment: Galaxy Genome Indexes
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'
        exclude: '*/tmp/* */work/* bin/*'
      location:
        path: /cvmfs/data.galaxyproject.org/byhand/location
        comment: Galaxy Data Location Files
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'
      managed:
        path: /cvmfs/data.galaxyproject.org/managed
        comment: Managed Galaxy Data
        'use chroot': 'yes'
        uid: nobody
        gid: nobody
        'read only': 'yes'
        list: 'yes'

host_firewall_rules:
  - service: rsyncd
    state: enabled
    permanent: yes
    immediate: yes
  - port: 2377/tcp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 2377/tcp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/tcp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/tcp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/udp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 7946/udp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 4789/udp
    source: 129.114.17.191/32
    state: enabled
    permanent: yes
    immediate: yes
  - port: 4789/udp
    source: 149.165.168.157/32
    state: enabled
    permanent: yes
    immediate: yes

docker_daemon_bip: '172.17.0.1/17'
docker_swarm_network: '172.17.128.0/17'
docker_swarm_gateway: '172.17.128.1'

docker_ssl_ca_dn:
  country: US
  state: Pennsylvania
  locality: University Park
  organization: The Pennsylvania State University
  organizational_unit: The Galaxy Project
  common_name: Galaxy Docker CA Root

# datacache.galaxyproject.org
nginx_enable_default_server: false
nginx_configs:
  - datacache
