---

certbotservers_group_directories:
  - path: "{{ certbot_well_known_root }}"
    mode: "0755"

certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: "{{ nginx_srv }}/_well-known_root"
#certbot_share_key_users:
#  - "{{ nginx_conf_user }}"
certbot_post_renewal: |
    systemctl restart nginx || true
certbot_agree_tos: --agree-tos

nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/private/privkey.pem

telegraf_plugins_extra:
  x509_cert:
    config:
      - sources = ["https://{{ certbot_domains[0] }}:443"]
