---

# 500 GB why not
cvmfs_quota_limit: 512000

galaxy_cvmfs_repos_enabled: true

# override so that the TACC stratum 1 is always first
cvmfs_server_urls:
  - domain: galaxyproject.org
    use_geoapi: no
    urls:
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"

cvmfs_http_proxies:
  - "DIRECT"

galaxynodes_group_authorized_key_users:
  - name: g2test
    authorized: "{{ galaxy_team_users }}"
  - name: g2main
    authorized: "{{ galaxy_team_users }}"

galaxynodes_group_packages:
  - collectl
  - lzo
  - libcgroup-tools
  - singularity-runtime
  # packages for older tools
  - perl-Data-Dumper
  # Conda R does not package up all of its X dependencies
  # https://github.com/ContinuumIO/anaconda-issues/issues/4656
  - xorg-x11-apps
  - mesa-libGL

galaxynodes_group_files:
  - src: system/cleancgroups.py
    dest: ~root/cleancgroups.py

galaxynodes_group_crontabs:
  - id: clean_cgroups
    name: Clean old cgroups
    user: root
    minute: "*/5"
    job: "python /root/cleancgroups.py >> /var/log/cleancgroups.log 2>&1"
