---

dbservers_group_templates:
  - src: templates/stats/galaxy_db_slurp.sh.j2
    dest: /usr/local/bin/galaxy_db_slurp.sh
    owner: root
    group: root
    mode: '0755'

telegraf_plugins_extra:
  galaxy_db_slurp:
    plugin: "exec"
    config:
      - commands = ["/usr/local/bin/galaxy_db_slurp.sh"]
      - timeout = "120s"
      - data_format = "influx"
      - interval = "1m"
      - '[inputs.exec.tags]'
      - '  influxdb_database = "{{ galaxy_instance_codename }}_sql"'
  galaxy_tools_likely_broken_1w:
    plugin: "exec"
    config:
      - commands = ["/bin/bash -c 'PGDATABASE=galaxy_{{ galaxy_instance_codename }} /usr/local/bin/gxadmin iquery tool-likely-broken --short-tool-id 1'"]
      - timeout = "180s"
      - data_format = "influx"
      - interval = "15m"
      - '[inputs.exec.tags]'
      - '  influxdb_database = "{{ galaxy_instance_codename }}_sql"'
  galaxy_queue_by_tool:
    plugin: "exec"
    config:
      - commands = ["/bin/bash -c 'PGDATABASE=galaxy_{{ galaxy_instance_codename }} /usr/local/bin/gxadmin iquery queue --by tool'"]
      - timeout = "180s"
      - data_format = "influx"
      - interval = "1m"
      - '[inputs.exec.tags]'
      - '  influxdb_database = "{{ galaxy_instance_codename }}_sql"'
  galaxy_queue_by_destination:
    plugin: "exec"
    config:
      - commands = ["/bin/bash -c 'PGDATABASE=galaxy_{{ galaxy_instance_codename }} /usr/local/bin/gxadmin iquery queue --by destination'"]
      - timeout = "180s"
      - data_format = "influx"
      - interval = "1m"
      - '[inputs.exec.tags]'
      - '  influxdb_database = "{{ galaxy_instance_codename }}_sql"'
  #galaxy_queue_by_user:
  #  plugin: "exec"
  #  config:
  #    - commands = ["/bin/bash -c 'PGDATABASE=galaxy_{{ galaxy_instance_codename }} /usr/local/bin/gxadmin iquery queue --by user'"]
  #    - timeout = "180s"
  #    - data_format = "influx"
  #    - interval = "1m"
  #    - '[inputs.exec.tags]'
  #    - '  influxdb_database = "{{ galaxy_instance_codename }}_sql"'

gxadmin_dir: /usr/local/lib/gxadmin
gxadmin_bin_dir: /usr/local/bin
