---

#dns_bind_keys: "{{ vault_dns_bind_keys }} + {{ certbot_ddns_keys }}"
certbot_ddns_keys: "{{ vault_certbot_ddns_keys }}"
dns_bind_keys: "{{ certbot_ddns_keys }}"

dns_bind_options:
  - dnssec-validation: 'auto'
  - auth-nxdomain: 'no'
  - 'listen-on port 53': ['any']
  - recursion: 'no'
  - allow-recursion: ['none']
  - allow-transfer: ['none']
  - allow-query: ['any']
  - query-source: 'address * port *'

dns_bind_control_inet_specs:
  - '127.0.0.1 allow { localhost; }'

dns_bind_logging_channels:
  - name: 'default_debug'
    options:
      - file: '"data/named.run"'
      - severity: 'dynamic'

dns_bind_views:
  - name: 'global'
    match_clients:
      - 'any'
    zones:
      - file: 'student.galaxy.training.zone'
        dir: '/var/named/dynamic'
        update_policy:
          - 'grant certbot-training. zonesub TXT'
          - 'grant certbot-training. wildcard *.interactivetoolentrypoint.interactivetool.*.student.galaxy.training. TXT'
