---

influxdb_client_pass: "{{ vault_influxdb_client_pass }}"

# run telegraf on everything
telegraf_agent_package_state: latest

telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["https://stats.galaxyproject.org:8086"]
    - username = "client"
    - password = "{{ influxdb_client_pass }}"
    - database = "system"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
